[workspace]
# A separate workspace

[package]
name = "sea-query-rusqlite"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = { version = "1" }
rusqlite = { version = "0.29" }
sea-query = { version = "0.30" }
sea-query-rusqlite = { version = "0.4" }
firedbg-lib = "0.1"
